import type { VFSNode, SerializedVFSNode } from './types';
import { safePersist } from './storage';

const VFS_STORAGE_KEY = 'pocketterm-vfs';
const PROTECTED_SYSTEM_PATHS = [
  '/bin',
  '/boot',
  '/dev',
  '/etc',
  '/lib',
  '/lib64',
  '/proc',
  '/root',
  '/sbin',
  '/sys',
  '/usr',
  '/var',
];

function createNode(
  name: string,
  type: 'file' | 'directory',
  content: string,
  owner: string,
  group: string,
  permissions: string,
  children?: Map<string, VFSNode>
): VFSNode {
  return {
    name,
    type,
    content,
    owner,
    group,
    permissions,
    children: children ?? (type === 'directory' ? new Map() : undefined),
  };
}

function n(name: string, content: string, owner: string, group: string, perms: string): VFSNode {
  return createNode(name, 'file', content, owner, group, perms);
}
function d(name: string, owner: string, group: string, perms: string): VFSNode {
  return createNode(name, 'directory', '', owner, group, perms);
}

function getDefaultRoot(): VFSNode {
  const root = d('/', 'root', 'root', '755');

  // ── /bin ──
  const bin = d('bin', 'root', 'root', '755');
  for (const cmd of ['bash', 'sh', 'ls', 'cat', 'cp', 'mv', 'rm', 'mkdir', 'echo', 'grep', 'pwd', 'chmod', 'chown', 'touch', 'find', 'head', 'tail', 'wc', 'uname', 'hostname', 'mount', 'umount', 'login', 'su', 'df', 'dmesg']) {
    bin.children!.set(cmd, n(cmd, '', 'root', 'root', '755'));
  }
  root.children!.set('bin', bin);

  // ── /sbin ──
  const sbin = d('sbin', 'root', 'root', '755');
  for (const cmd of ['init', 'shutdown', 'reboot', 'ifconfig', 'ip', 'route', 'fsck', 'fdisk', 'iptables', 'modprobe']) {
    sbin.children!.set(cmd, n(cmd, '', 'root', 'root', '755'));
  }
  root.children!.set('sbin', sbin);

  // ── /boot ──
  const boot = d('boot', 'root', 'root', '755');
  boot.children!.set(
    'vmlinuz-5.14.0-362.8.1.el9_3.x86_64',
    n('vmlinuz-5.14.0-362.8.1.el9_3.x86_64', '[binary: Linux kernel image]', 'root', 'root', '600')
  );
  boot.children!.set(
    'initramfs-5.14.0-362.8.1.el9_3.x86_64.img',
    n('initramfs-5.14.0-362.8.1.el9_3.x86_64.img', '[binary: initial ramdisk image]', 'root', 'root', '644')
  );
  boot.children!.set(
    'grub2',
    d('grub2', 'root', 'root', '755')
  );
  boot.children!.get('grub2')!.children!.set(
    'grub.cfg',
    n('grub.cfg', [
      '# GRUB2 configuration - DO NOT EDIT',
      'set default="0"',
      'set timeout=5',
      'menuentry \'Rocky Linux (5.14.0-362.8.1.el9_3.x86_64) 9.3\' {',
      '  linux /vmlinuz-5.14.0-362.8.1.el9_3.x86_64 root=/dev/sda1 ro',
      '  initrd /initramfs-5.14.0-362.8.1.el9_3.x86_64.img',
      '}',
    ].join('\n') + '\n', 'root', 'root', '600')
  );
  root.children!.set('boot', boot);

  // ── /etc ──
  const etc = d('etc', 'root', 'root', '755');
  etc.children!.set('hostname', n('hostname', 'pocket-term\n', 'root', 'root', '644'));
  etc.children!.set(
    'os-release',
    n('os-release', [
      'NAME="Rocky Linux"',
      'VERSION="9.4 (Blue Onyx)"',
      'ID="rocky"',
      'ID_LIKE="rhel centos fedora"',
      'VERSION_ID="9.4"',
      'PLATFORM_ID="platform:el9"',
      'PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"',
      'ANSI_COLOR="0;32"',
      'LOGO="fedora-logo-icon"',
      'CPE_NAME="cpe:/o:rocky:rocky:9:4"',
      'HOME_URL="https://rockylinux.org/"',
      'BUG_REPORT_URL="https://bugs.rockylinux.org/"',
      'ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"',
      'ROCKY_SUPPORT_PRODUCT_VERSION="9.4"',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  etc.children!.set(
    'hosts',
    n('hosts', [
      '# /etc/hosts',
      '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4',
      '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  etc.children!.set(
    'motd',
    n('motd', [
      'Welcome to Rocky Linux 9.3 (Blue Onyx).',
      'This system is for authorized use only.',
      'Type "help" for available commands.',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  etc.children!.set(
    'resolv.conf',
    n('resolv.conf', [
      '# Generated by NetworkManager',
      'nameserver 8.8.8.8',
      'nameserver 8.8.4.4',
      'search localdomain',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  etc.children!.set(
    'passwd',
    n('passwd', [
      'root:x:0:0:root:/root:/bin/bash',
      'bin:x:1:1:bin:/bin:/sbin/nologin',
      'daemon:x:2:2:daemon:/sbin:/sbin/nologin',
      'adm:x:3:4:adm:/var/adm:/sbin/nologin',
      'lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin',
      'sync:x:5:0:sync:/sbin:/bin/sync',
      'shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown',
      'halt:x:7:0:halt:/sbin:/sbin/halt',
      'mail:x:8:12:mail:/var/spool/mail:/sbin/nologin',
      'operator:x:11:0:operator:/root:/sbin/nologin',
      'nobody:x:65534:65534:Kernel Overflow User:/:/sbin/nologin',
      'systemd-coredump:x:999:997:systemd Core Dumper:/:/sbin/nologin',
      'dbus:x:81:81:System message bus:/:/sbin/nologin',
      'polkitd:x:998:996:User for polkitd:/:/sbin/nologin',
      'sshd:x:74:74:Privilege-separated SSH:/usr/share/empty.sshd:/sbin/nologin',
      'guest:x:1000:1000:Guest User:/home/guest:/bin/bash',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  etc.children!.set(
    'shadow',
    n('shadow', [
      'root:$6$rounds=4096$fakesalt$fakehashedpasswordroot::0:99999:7:::',
      'bin:*:19469:0:99999:7:::',
      'daemon:*:19469:0:99999:7:::',
      'adm:*:19469:0:99999:7:::',
      'nobody:*:19469:0:99999:7:::',
      'sshd:!!:19836::::::',
      'guest:$6$rounds=4096$fakesalt$fakehashedpasswordguest::0:99999:7:::',
    ].join('\n') + '\n', 'root', 'root', '000')
  );
  etc.children!.set(
    'group',
    n('group', [
      'root:x:0:',
      'bin:x:1:',
      'daemon:x:2:',
      'wheel:x:10:guest',
      'guest:x:1000:',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  etc.children!.set(
    'shells',
    n('shells', [
      '/bin/sh',
      '/bin/bash',
      '/usr/bin/sh',
      '/usr/bin/bash',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  etc.children!.set(
    'fstab',
    n('fstab', [
      '# /etc/fstab',
      '# Created by anaconda on Mon Jan  1 00:00:00 2024',
      '#',
      '# <file system>        <mount point>  <type>  <options>         <dump>  <pass>',
      '/dev/sda1              /              ext4    defaults          1       1',
      '/dev/sda2              /boot          ext4    defaults          1       2',
      '/dev/sda3              none           swap    sw                0       0',
      'tmpfs                  /tmp           tmpfs   defaults,noexec   0       0',
      'devpts                 /dev/pts       devpts  gid=5,mode=620    0       0',
      'sysfs                  /sys           sysfs   defaults          0       0',
      'proc                   /proc          proc    defaults          0       0',
    ].join('\n') + '\n', 'root', 'root', '644')
  );

  // /etc/NetworkManager/system-connections
  const networkManager = d('NetworkManager', 'root', 'root', '755');
  const systemConnections = d('system-connections', 'root', 'root', '700');
  systemConnections.children!.set(
    'eth0.nmconnection',
    n('eth0.nmconnection', [
      '[connection]',
      'id=eth0',
      'uuid=a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      'type=ethernet',
      'interface-name=eth0',
      '',
      '[ipv4]',
      'method=manual',
      'address1=192.168.1.100/24',
      'gateway=192.168.1.1',
      'dns=8.8.8.8;8.8.4.4;',
      '',
      '[ipv6]',
      'method=auto',
      '',
      '[ethernet]',
      'mac-address=52:54:00:12:34:56',
    ].join('\n') + '\n', 'root', 'root', '600')
  );
  networkManager.children!.set('system-connections', systemConnections);
  etc.children!.set('NetworkManager', networkManager);

  root.children!.set('etc', etc);

  // ── /proc (virtual filesystem) ──
  const proc = d('proc', 'root', 'root', '555');
  proc.children!.set(
    'cpuinfo',
    n('cpuinfo', [
      'processor\t: 0',
      'vendor_id\t: GenuineIntel',
      'cpu family\t: 6',
      'model\t\t: 142',
      'model name\t: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz',
      'stepping\t: 10',
      'microcode\t: 0xf0',
      'cpu MHz\t\t: 1992.000',
      'cache size\t: 8192 KB',
      'physical id\t: 0',
      'siblings\t: 4',
      'core id\t\t: 0',
      'cpu cores\t: 4',
      'fpu\t\t: yes',
      'flags\t\t: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault pti ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 smep bmi2 erms rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves',
      'bogomips\t: 3984.00',
      'clflush size\t: 64',
      'cache_alignment\t: 64',
      'address sizes\t: 39 bits physical, 48 bits virtual',
      '',
      'processor\t: 1',
      'vendor_id\t: GenuineIntel',
      'cpu family\t: 6',
      'model\t\t: 142',
      'model name\t: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz',
      'stepping\t: 10',
      'cpu MHz\t\t: 1992.000',
      'cache size\t: 8192 KB',
      'physical id\t: 0',
      'siblings\t: 4',
      'core id\t\t: 1',
      'cpu cores\t: 4',
      'bogomips\t: 3984.00',
    ].join('\n') + '\n', 'root', 'root', '444')
  );
  proc.children!.set(
    'meminfo',
    n('meminfo', [
      'MemTotal:        8052976 kB',
      'MemFree:         2841232 kB',
      'MemAvailable:    5624148 kB',
      'Buffers:          234512 kB',
      'Cached:          2548404 kB',
      'SwapCached:            0 kB',
      'Active:          3124688 kB',
      'Inactive:        1687456 kB',
      'Active(anon):    2029232 kB',
      'Inactive(anon):      384 kB',
      'Active(file):    1095456 kB',
      'Inactive(file):  1687072 kB',
      'SwapTotal:       2097148 kB',
      'SwapFree:        2097148 kB',
      'Dirty:                 0 kB',
      'Writeback:             0 kB',
      'AnonPages:       2029044 kB',
      'Mapped:           512736 kB',
      'Shmem:               768 kB',
      'KReclaimable:     399600 kB',
      'Slab:             543216 kB',
      'SReclaimable:     399600 kB',
      'SUnreclaim:       143616 kB',
      'KernelStack:       12288 kB',
      'PageTables:        41984 kB',
      'HugePages_Total:       0',
      'HugePages_Free:        0',
      'Hugepagesize:       2048 kB',
    ].join('\n') + '\n', 'root', 'root', '444')
  );
  proc.children!.set(
    'version',
    n('version', 'Linux version 5.14.0-362.8.1.el9_3.x86_64 (mockbuild@rocky9-build.rockylinux.org) (gcc (GCC) 11.4.1 20230605 (Rocky Linux 11.4.1-2.1.el9), GNU ld version 2.35.2-42.el9) #1 SMP PREEMPT_DYNAMIC Wed Nov 8 17:39:03 UTC 2023\n', 'root', 'root', '444')
  );
  proc.children!.set(
    'uptime',
    n('uptime', '3842.71 14937.28\n', 'root', 'root', '444')
  );
  root.children!.set('proc', proc);

  // ── /var ──
  const varDir = d('var', 'root', 'root', '755');
  const logDir = d('log', 'root', 'root', '755');
  logDir.children!.set(
    'messages',
    n('messages', [
      'Jan  1 00:00:01 pocket-term systemd[1]: Starting systemd...',
      'Jan  1 00:00:02 pocket-term systemd[1]: Started systemd.',
      'Jan  1 00:00:02 pocket-term kernel: Linux version 5.14.0-362.8.1.el9_3.x86_64 (mockbuild@build.rockylinux.org)',
      'Jan  1 00:00:03 pocket-term kernel: Command line: BOOT_IMAGE=(hd0,msdos1)/vmlinuz-5.14.0-362.8.1.el9_3.x86_64',
      'Jan  1 00:00:04 pocket-term NetworkManager[1234]: <info>  [0.000000] NetworkManager version 1.40.0 starting',
      'Jan  1 00:00:05 pocket-term NetworkManager[1234]: <info>  [0.001000] eth0: link up, 1000Mb/s',
      'Jan  1 00:00:06 pocket-term systemd[1]: Reached target Multi-User System.',
    ].join('\n') + '\n', 'root', 'root', '640')
  );
  logDir.children!.set(
    'secure',
    n('secure', [
      'Jan  1 00:00:03 pocket-term sshd[2048]: Server listening on 0.0.0.0 port 22.',
      'Jan  1 00:00:03 pocket-term sshd[2048]: Server listening on :: port 22.',
      'Jan  1 00:00:10 pocket-term login[3120]: pam_unix(login:session): session opened for user guest(uid=1000) by LOGIN(uid=0)',
      'Jan  1 00:00:12 pocket-term su[3245]: (to root) guest on pts/0',
      'Jan  1 00:00:15 pocket-term sudo: guest : TTY=pts/0 ; PWD=/home/guest ; USER=root ; COMMAND=/bin/dnf install htop',
    ].join('\n') + '\n', 'root', 'root', '600')
  );
  logDir.children!.set(
    'dnf.log',
    n('dnf.log', [
      '2024-01-01T00:00:06+0000 INFO --- logging initialized ---',
      '2024-01-01T00:00:06+0000 DDEBUG timer: config: 8 ms',
      '2024-01-01T00:00:06+0000 DEBUG Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync',
      '2024-01-01T00:00:07+0000 INFO Metadata cache refreshed recently.',
      '2024-01-01T00:00:07+0000 DDEBUG Base command: list',
      '2024-01-01T00:00:07+0000 INFO Last metadata expiration check: 0:12:34 ago.',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  logDir.children!.set(
    'boot.log',
    n('boot.log', [
      '[  OK  ] Started Show Plymouth Boot Screen.',
      '[  OK  ] Started Forward Password Requests to Plymouth.',
      '[  OK  ] Reached target Local Encrypted Volumes.',
      '[  OK  ] Found device /dev/sda1.',
      '[  OK  ] Started File System Check on /dev/sda1.',
      '[  OK  ] Mounted /boot.',
      '[  OK  ] Reached target Local File Systems.',
      '[  OK  ] Started Permit User Sessions.',
      '         Starting GNOME Display Manager...',
      '[  OK  ] Started GNOME Display Manager.',
    ].join('\n') + '\n', 'root', 'root', '644')
  );
  varDir.children!.set('log', logDir);
  root.children!.set('var', varDir);

  // ── /dev ──
  const dev = d('dev', 'root', 'root', '755');
  dev.children!.set('null', n('null', '', 'root', 'root', '666'));
  dev.children!.set('zero', n('zero', '', 'root', 'root', '666'));
  dev.children!.set('random', n('random', '', 'root', 'root', '666'));
  dev.children!.set('urandom', n('urandom', '', 'root', 'root', '666'));
  dev.children!.set('tty', n('tty', '', 'root', 'root', '666'));
  dev.children!.set('sda', n('sda', '', 'root', 'root', '660'));
  dev.children!.set('sda1', n('sda1', '', 'root', 'root', '660'));
  dev.children!.set('sda2', n('sda2', '', 'root', 'root', '660'));
  dev.children!.set('sda3', n('sda3', '', 'root', 'root', '660'));
  const pts = d('pts', 'root', 'root', '755');
  pts.children!.set('0', n('0', '', 'guest', 'guest', '620'));
  dev.children!.set('pts', pts);
  root.children!.set('dev', dev);

  // ── /usr ──
  const usr = d('usr', 'root', 'root', '755');
  const usrBin = d('bin', 'root', 'root', '755');
  for (const cmd of ['ls', 'cat', 'pwd', 'cd', 'env', 'id', 'whoami', 'man', 'less', 'more', 'sort', 'uniq', 'cut', 'tr', 'tee', 'xargs', 'dirname', 'basename', 'realpath', 'stat', 'file', 'diff', 'patch', 'tar', 'gzip', 'bzip2', 'xz', 'curl']) {
    usrBin.children!.set(cmd, n(cmd, '', 'root', 'root', '755'));
  }
  usr.children!.set('bin', usrBin);
  const usrSbin = d('sbin', 'root', 'root', '755');
  for (const cmd of ['useradd', 'userdel', 'groupadd', 'groupdel', 'chroot', 'nologin']) {
    usrSbin.children!.set(cmd, n(cmd, '', 'root', 'root', '755'));
  }
  usr.children!.set('sbin', usrSbin);
  const usrLib = d('lib', 'root', 'root', '755');
  usr.children!.set('lib', usrLib);
  const usrLib64 = d('lib64', 'root', 'root', '755');
  usr.children!.set('lib64', usrLib64);
  const usrLocal = d('local', 'root', 'root', '755');
  usrLocal.children!.set('bin', d('bin', 'root', 'root', '755'));
  usr.children!.set('local', usrLocal);
  const usrShare = d('share', 'root', 'root', '755');
  const usrShareMan = d('man', 'root', 'root', '755');
  const man1Dir = d('man1', 'root', 'root', '755');
  man1Dir.children!.set(
    'pocketterm.1',
    n('pocketterm.1', [
      'POCKETTERM(1)                User Commands                POCKETTERM(1)',
      '',
      'NAME',
      '       pocketterm - The PocketTerm Environment Manager',
      '',
      'SYNOPSIS',
      '       pocketterm',
      '',
      'DESCRIPTION',
      '       pocketterm is the primary control utility for the PocketTerm runtime.',
      '       It manages a virtualized execution environment that provides a persistent',
      '       Filesystem Hierarchy Standard (FHS) layout and an AST-based command',
      '       interpreter for interactive shell operations.',
      '',
      'INTERACTIVE MODE',
      '       Invoking pocketterm launches a text user interface (TUI) used for',
      '       environment control tasks. The interface provides diagnostic review',
      '       surfaces and onboarding workflows for new users entering the shell.',
      '',
      'PERSISTENCE',
      '       File modifications and package state maintained through dnf are committed',
      '       to non-volatile local storage. Persisted state remains available across',
      '       power cycles initiated through reboot.',
      '',
      'ENVIRONMENT',
      '       Default user context initializes at /home/guest. Command resolution',
      '       follows the standard executable search path rooted at /usr/bin.',
      '',
      'SEE ALSO',
      '       man(1), dnf(8), reboot(8), bash(1)',
      '',
    ].join('\n'), 'root', 'root', '644')
  );
  usrShareMan.children!.set('man1', man1Dir);
  usrShare.children!.set('man', usrShareMan);
  const usrShareDoc = d('doc', 'root', 'root', '755');
  usrShare.children!.set('doc', usrShareDoc);
  usr.children!.set('share', usrShare);
  root.children!.set('usr', usr);

  // ── /lib and /lib64 (symlink-like) ──
  root.children!.set('lib', d('lib', 'root', 'root', '755'));
  root.children!.set('lib64', d('lib64', 'root', 'root', '755'));

  // ── /home/guest ──
  const home = d('home', 'root', 'root', '755');
  const guestHome = d('guest', 'guest', 'guest', '755');
  guestHome.children!.set('.bashrc', n('.bashrc', [
    '# .bashrc',
    '',
    '# Source global definitions',
    'if [ -f /etc/bashrc ]; then',
    '    . /etc/bashrc',
    'fi',
    '',
    '# User specific aliases and functions',
    'alias ll=\'ls -l\'',
    'alias la=\'ls -la\'',
    '',
    '# Uncomment to change prompt:',
    '# PS1="[\\u@\\h \\W]\\$ "',
  ].join('\n') + '\n', 'guest', 'guest', '644'));
  guestHome.children!.set('.bash_profile', n('.bash_profile', [
    '# .bash_profile',
    '',
    '# Get the aliases and functions',
    'if [ -f ~/.bashrc ]; then',
    '    . ~/.bashrc',
    'fi',
    '',
    '# User specific environment and startup programs',
    'PATH=$PATH:$HOME/.local/bin:$HOME/bin',
    'export PATH',
  ].join('\n') + '\n', 'guest', 'guest', '644'));
  guestHome.children!.set('.bash_history', n('.bash_history', '', 'guest', 'guest', '600'));
  const guestDocuments = d('Documents', 'guest', 'guest', '755');
  guestHome.children!.set('Documents', guestDocuments);
  const guestDownloads = d('Downloads', 'guest', 'guest', '755');
  guestHome.children!.set('Downloads', guestDownloads);
  home.children!.set('guest', guestHome);
  root.children!.set('home', home);

  // ── /root ──
  const rootHome = d('root', 'root', 'root', '700');
  rootHome.children!.set('.bashrc', n('.bashrc', [
    '# .bashrc',
    'alias ll=\'ls -l\'',
    'alias la=\'ls -la\'',
    'export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin',
  ].join('\n') + '\n', 'root', 'root', '644'));
  rootHome.children!.set('.bash_history', n('.bash_history', '', 'root', 'root', '600'));
  root.children!.set('root', rootHome);

  // ── /tmp ──
  const tmp = d('tmp', 'root', 'root', '1777');
  root.children!.set('tmp', tmp);

  // ── /sys ──
  root.children!.set('sys', d('sys', 'root', 'root', '555'));

  // ── /run ──
  root.children!.set('run', d('run', 'root', 'root', '755'));

  // ── /opt ──
  root.children!.set('opt', d('opt', 'root', 'root', '755'));

  // ── /mnt ──
  root.children!.set('mnt', d('mnt', 'root', 'root', '755'));

  // ── /media ──
  root.children!.set('media', d('media', 'root', 'root', '755'));

  // ── /srv ──
  root.children!.set('srv', d('srv', 'root', 'root', '755'));

  return root;
}

function normalizePath(path: string): string {
  const parts = path.split('/').filter(Boolean);
  const result: string[] = [];
  for (const p of parts) {
    if (p === '.') continue;
    if (p === '..') {
      result.pop();
      continue;
    }
    result.push(p);
  }
  return '/' + result.join('/');
}

function pathToParts(path: string): string[] {
  const normalized = normalizePath(path).replace(/^\//, '').replace(/\/$/, '');
  return normalized ? normalized.split('/') : [];
}

function nodeToSerializable(node: VFSNode): SerializedVFSNode {
  const result: SerializedVFSNode = {
    name: node.name,
    type: node.type,
    content: node.content,
    owner: node.owner,
    group: node.group,
    permissions: node.permissions,
  };
  if (node.children && node.children.size > 0) {
    result.children = {};
    node.children.forEach((child, key) => {
      result.children![key] = nodeToSerializable(child);
    });
  }
  return result;
}

function serializableToNode(s: SerializedVFSNode): VFSNode {
  const node: VFSNode = {
    name: s.name,
    type: s.type,
    content: s.content,
    owner: s.owner,
    group: s.group ?? s.owner, // backward compat: old data has no group
    permissions: s.permissions,
  };
  if (s.children && Object.keys(s.children).length > 0) {
    node.children = new Map();
    Object.entries(s.children).forEach(([key, child]) => {
      node.children!.set(key, serializableToNode(child));
    });
  }
  return node;
}

/** Critical system paths that must exist for the kernel to function. */
const CRITICAL_PATHS = ['/bin', '/boot', '/etc', '/usr', '/var', '/home', '/tmp'];

export class FileSystem {
  private root: VFSNode;
  private currentUser: string;

  private ensureDirectory(path: string, owner: string, group: string, perms: string): void {
    const normalized = normalizePath(path);
    if (normalized === '/') return;
    const parts = normalized.split('/').filter(Boolean);
    let cursor = this.root;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (!cursor.children) cursor.children = new Map();
      let child = cursor.children.get(part);
      if (!child) {
        const isLeaf = i === parts.length - 1;
        child = d(part, isLeaf ? owner : 'root', isLeaf ? group : 'root', isLeaf ? perms : '755');
        cursor.children.set(part, child);
      }
      if (child.type !== 'directory') return;
      cursor = child;
    }
  }

  private ensureFile(path: string, content: string, owner: string, group: string, perms: string): void {
    const normalized = normalizePath(path);
    const info = this.getParent(normalized);
    if (!info) return;
    const { parent, name } = info;
    if (parent.type !== 'directory') return;
    if (!parent.children) parent.children = new Map();
    if (!parent.children.has(name)) {
      parent.children.set(name, n(name, content, owner, group, perms));
    }
  }

  private ensureBaselineStructure(): void {
    // Top-level FHS directories expected in Rocky-like environments.
    for (const path of [
      '/bin', '/boot', '/dev', '/etc', '/home', '/lib', '/lib64', '/media', '/mnt',
      '/opt', '/proc', '/root', '/run', '/sbin', '/srv', '/sys', '/tmp', '/usr', '/var',
    ]) {
      this.ensureDirectory(path, 'root', 'root', path === '/tmp' ? '1777' : '755');
    }

    // Required deep hierarchy used by command lookup and manual pages.
    for (const path of [
      '/usr/bin',
      '/usr/lib',
      '/usr/lib64',
      '/usr/local',
      '/usr/local/bin',
      '/usr/share',
      '/usr/share/man',
      '/usr/share/man/man1',
      '/var/log',
      '/home/guest',
    ]) {
      const owner = path === '/home/guest' ? 'guest' : 'root';
      const group = path === '/home/guest' ? 'guest' : 'root';
      const perms = path === '/home/guest' ? '755' : '755';
      this.ensureDirectory(path, owner, group, perms);
    }

    this.ensureFile('/etc/shells', '/bin/sh\n/bin/bash\n/usr/bin/sh\n/usr/bin/bash\n', 'root', 'root', '644');
    this.ensureFile('/var/log/messages', '', 'root', 'root', '640');
    this.ensureFile('/var/log/secure', '', 'root', 'root', '600');
    this.ensureFile('/var/log/dnf.log', '', 'root', 'root', '644');
    this.ensureFile('/usr/share/man/man1/pocketterm.1', [
      'POCKETTERM(1)                User Commands                POCKETTERM(1)',
      '',
      'NAME',
      '       pocketterm - The PocketTerm Environment Manager',
      '',
      'SYNOPSIS',
      '       pocketterm',
      '',
      'DESCRIPTION',
      '       pocketterm is the primary control utility for the PocketTerm runtime.',
      '       It manages a virtualized execution environment that provides a persistent',
      '       Filesystem Hierarchy Standard (FHS) layout and an AST-based command',
      '       interpreter for interactive shell operations.',
      '',
      'INTERACTIVE MODE',
      '       Invoking pocketterm launches a text user interface (TUI) used for',
      '       environment control tasks. The interface provides diagnostic review',
      '       surfaces and onboarding workflows for new users entering the shell.',
      '',
      'PERSISTENCE',
      '       File modifications and package state maintained through dnf are committed',
      '       to non-volatile local storage. Persisted state remains available across',
      '       power cycles initiated through reboot.',
      '',
      'ENVIRONMENT',
      '       Default user context initializes at /home/guest. Command resolution',
      '       follows the standard executable search path rooted at /usr/bin.',
      '',
      'SEE ALSO',
      '       man(1), dnf(8), reboot(8), bash(1)',
      '',
    ].join('\n'), 'root', 'root', '644');
  }

  private ensureBaselineFiles(): void {
    const etc = this.getNode('/etc');
    if (!etc || etc.type !== 'directory') return;
    if (!etc.children) etc.children = new Map();
    if (!etc.children.has('motd')) {
      etc.children.set(
        'motd',
        n('motd', [
          'Welcome to Rocky Linux 9.3 (Blue Onyx).',
          'This system is for authorized use only.',
          'Type "help" for available commands.',
        ].join('\n') + '\n', 'root', 'root', '644')
      );
      this.persist();
    }
  }

  constructor(currentUser: string = 'guest') {
    this.currentUser = currentUser;
    const stored = localStorage.getItem(VFS_STORAGE_KEY);
    if (stored) {
      try {
        const parsed = JSON.parse(stored) as SerializedVFSNode;
        this.root = serializableToNode(parsed);
      } catch {
        this.root = getDefaultRoot();
      }
    } else {
      this.root = getDefaultRoot();
    }
    this.ensureBaselineStructure();
    this.ensureBaselineFiles();
    this.persist();
  }

  private _lastPersistError: string | null = null;

  persist(): boolean {
    const { ok, error } = safePersist(VFS_STORAGE_KEY, JSON.stringify(nodeToSerializable(this.root)));
    this._lastPersistError = ok ? null : (error ?? 'unknown error');
    return ok;
  }

  getLastPersistError(): string | null {
    return this._lastPersistError;
  }

  resolvePath(cwd: string, path: string): string {
    let p = path;
    if (p.startsWith('~/') || p === '~') {
      const home = this.currentUser === 'root' ? '/root' : `/home/${this.currentUser}`;
      p = p === '~' ? home : home + p.slice(1);
    }
    if (!p.startsWith('/')) {
      const base = cwd.endsWith('/') ? cwd.slice(0, -1) : cwd || '/';
      p = base === '/' ? `/${p}` : `${base}/${p}`;
    }
    return normalizePath(p);
  }

  getNode(path: string): VFSNode | null {
    const parts = pathToParts(path);
    if (parts.length === 0) return this.root;

    let current: VFSNode = this.root;
    for (const part of parts) {
      if (part === '.' || part === '') continue;
      const child = current.children?.get(part);
      if (!child) return null;
      current = child;
    }
    return current;
  }

  getParent(path: string): { parent: VFSNode; name: string } | null {
    const parts = pathToParts(path);
    if (parts.length <= 1) return { parent: this.root, name: parts[0] || '/' };

    const parentPath = '/' + parts.slice(0, -1).join('/');
    const name = parts[parts.length - 1];
    const parent = this.getNode(parentPath);
    return parent ? { parent, name } : null;
  }

  private getGroupForUser(user: string): string {
    return user; // simplified: each user's primary group matches their username
  }

  canRead(node: VFSNode, user: string): boolean {
    if (user === 'root') return true;
    const perms = node.permissions;
    if (node.owner === user) return (parseInt(perms[0], 10) & 4) !== 0;
    if (node.group === this.getGroupForUser(user)) return (parseInt(perms[1], 10) & 4) !== 0;
    return (parseInt(perms[2], 10) & 4) !== 0;
  }

  canWrite(node: VFSNode, user: string): boolean {
    if (user === 'root') return true;
    const perms = node.permissions;
    if (node.owner === user) return (parseInt(perms[0], 10) & 2) !== 0;
    if (node.group === this.getGroupForUser(user)) return (parseInt(perms[1], 10) & 2) !== 0;
    return (parseInt(perms[2], 10) & 2) !== 0;
  }

  canExecute(node: VFSNode, user: string): boolean {
    if (user === 'root') return true;
    const perms = node.permissions;
    if (node.owner === user) return (parseInt(perms[0], 10) & 1) !== 0;
    if (node.group === this.getGroupForUser(user)) return (parseInt(perms[1], 10) & 1) !== 0;
    return (parseInt(perms[2], 10) & 1) !== 0;
  }

  requiresSudo(node: VFSNode): boolean {
    return node.owner === 'root' && this.currentUser !== 'root';
  }

  listDir(path: string, user: string): string[] {
    const node = this.getNode(path);
    if (!node || node.type !== 'directory') return [];
    if (!this.canRead(node, user)) return [];
    return Array.from(node.children?.keys() ?? []).sort();
  }

  readFile(path: string, user: string): string | null {
    const node = this.getNode(path);
    if (!node || node.type !== 'file') return null;
    if (!this.canRead(node, user)) return null;
    return node.content;
  }

  writeFile(path: string, content: string, user: string, sudo: boolean): boolean {
    const info = this.getParent(path);
    if (!info) return false;
    const { parent, name } = info;
    if (parent.type !== 'directory') return false;
    if (!this.canWrite(parent, sudo ? 'root' : user)) return false;

    const existing = parent.children?.get(name);
    if (existing) {
      if (existing.type !== 'file') return false;
      if (!this.canWrite(existing, sudo ? 'root' : user)) return false;
    }

    const node = createNode(
      name, 'file', content,
      existing?.owner ?? user,
      existing?.group ?? (user === 'root' ? 'root' : user),
      existing?.permissions ?? '644'
    );
    if (!parent.children) parent.children = new Map();
    parent.children.set(name, node);
    this.persist();
    return true;
  }

  mkdir(path: string, user: string, sudo: boolean): boolean {
    const info = this.getParent(path);
    if (!info) return false;
    const { parent, name } = info;
    if (parent.type !== 'directory') return false;
    if (!this.canWrite(parent, sudo ? 'root' : user)) return false;
    if (parent.children?.has(name)) return false;

    const node = createNode(name, 'directory', '', user, user === 'root' ? 'root' : user, '755');
    if (!parent.children) parent.children = new Map();
    parent.children.set(name, node);
    this.persist();
    return true;
  }

  remove(path: string, user: string, sudo: boolean, recursive: boolean): boolean {
    const normalized = normalizePath(path);
    if (PROTECTED_SYSTEM_PATHS.some((p) => normalized === p || normalized.startsWith(`${p}/`))) {
      return false;
    }

    const info = this.getParent(path);
    if (!info) return false;
    const { parent, name } = info;
    const node = parent.children?.get(name);
    if (!node) return false;
    if (!this.canWrite(parent, sudo ? 'root' : user)) return false;

    if (node.type === 'directory' && (node.children?.size ?? 0) > 0 && !recursive) {
      return false;
    }

    if (node.type === 'directory' && recursive && node.children) {
      const childNames = Array.from(node.children.keys());
      for (const childName of childNames) {
        const childPath = path.endsWith('/') ? path + childName : path + '/' + childName;
        if (!this.remove(childPath, user, sudo, true)) return false;
      }
    }

    parent.children!.delete(name);
    this.persist();
    return true;
  }

  chmod(path: string, mode: string, user: string, sudo: boolean): boolean {
    const node = this.getNode(path);
    if (!node) return false;
    if (node.owner !== user && user !== 'root' && !sudo) return false;
    if (/^[0-7]{3,4}$/.test(mode)) {
      node.permissions = mode.length === 4 ? mode.slice(1) : mode;
      this.persist();
      return true;
    }
    return false;
  }

  chown(path: string, newOwner: string, newGroup: string | null, user: string, sudo: boolean): boolean {
    const node = this.getNode(path);
    if (!node) return false;
    if (user !== 'root' && !sudo) return false;
    node.owner = newOwner;
    if (newGroup !== null) node.group = newGroup;
    this.persist();
    return true;
  }

  /** Returns true if any critical system path is missing from the VFS. */
  checkCriticalPathsMissing(): boolean {
    for (const p of CRITICAL_PATHS) {
      if (!this.getNode(p)) return true;
    }
    return false;
  }

  setCurrentUser(user: string): void {
    this.currentUser = user;
  }

  getCurrentUser(): string {
    return this.currentUser;
  }

  resetToDefault(): void {
    localStorage.removeItem(VFS_STORAGE_KEY);
    this.root = getDefaultRoot();
  }

  /** Create a small, non-persisted remote server VFS. */
  static createRemoteVFS(user: string): FileSystem {
    const remote = new FileSystem(user);
    // Overwrite root with a minimal remote server tree (no localStorage)
    const root = d('/', 'root', 'root', '755');

    const etc = d('etc', 'root', 'root', '755');
    etc.children!.set('hostname', n('hostname', 'server01\n', 'root', 'root', '644'));
    etc.children!.set('os-release', n('os-release', [
      'NAME="Rocky Linux"',
      'VERSION="9.4 (Blue Onyx)"',
      'PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"',
    ].join('\n') + '\n', 'root', 'root', '644'));
    etc.children!.set('hosts', n('hosts', '127.0.0.1 localhost\n10.0.0.50 server01\n', 'root', 'root', '644'));
    etc.children!.set('passwd', n('passwd', 'root:x:0:0:root:/root:/bin/bash\nadmin:x:1000:1000:Admin:/home/admin:/bin/bash\n', 'root', 'root', '644'));
    root.children!.set('etc', etc);

    const bin = d('bin', 'root', 'root', '755');
    for (const cmd of ['bash', 'sh', 'ls', 'cat', 'cp', 'rm', 'mkdir', 'echo', 'grep']) {
      bin.children!.set(cmd, n(cmd, '', 'root', 'root', '755'));
    }
    root.children!.set('bin', bin);

    root.children!.set('boot', d('boot', 'root', 'root', '755'));

    const home = d('home', 'root', 'root', '755');
    const adminHome = d('admin', 'admin', 'admin', '755');
    adminHome.children!.set('.bashrc', n('.bashrc', '# admin bashrc\n', 'admin', 'admin', '644'));
    adminHome.children!.set('server-notes.txt', n('server-notes.txt', [
      '# Server01 Maintenance Log',
      '2024-01-15: Deployed v2.1.0 to production',
      '2024-01-20: Patched OpenSSL CVE-2024-0001',
      '2024-02-01: Upgraded kernel to 5.14.0-362.8.1.el9_3',
      '2024-02-10: Rotated TLS certificates',
    ].join('\n') + '\n', 'admin', 'admin', '644'));
    adminHome.children!.set('deploy.sh', n('deploy.sh', '#!/bin/bash\necho "Deploying application..."\nrsync -avz /opt/app/ /var/www/html/\nsystemctl restart nginx\necho "Deploy complete."\n', 'admin', 'admin', '755'));
    home.children!.set('admin', adminHome);
    root.children!.set('home', home);

    const rootHome = d('root', 'root', 'root', '700');
    rootHome.children!.set('.bashrc', n('.bashrc', '# root bashrc\n', 'root', 'root', '644'));
    root.children!.set('root', rootHome);

    const varDir = d('var', 'root', 'root', '755');
    const logDir = d('log', 'root', 'root', '755');
    logDir.children!.set('messages', n('messages', 'Jan 15 08:00:01 server01 systemd[1]: Started systemd.\nJan 15 08:00:02 server01 sshd[1234]: Server listening on 0.0.0.0 port 22.\n', 'root', 'root', '644'));
    const wwwDir = d('www', 'root', 'root', '755');
    const htmlDir = d('html', 'root', 'root', '755');
    htmlDir.children!.set('index.html', n('index.html', '<html><body><h1>Welcome to server01</h1></body></html>\n', 'root', 'root', '644'));
    wwwDir.children!.set('html', htmlDir);
    varDir.children!.set('log', logDir);
    varDir.children!.set('www', wwwDir);
    root.children!.set('var', varDir);

    root.children!.set('tmp', d('tmp', 'root', 'root', '1777'));
    root.children!.set('opt', d('opt', 'root', 'root', '755'));

    // Replace the root directly (bypass localStorage)
    (remote as unknown as { root: VFSNode }).root = root;
    remote.setCurrentUser(user);
    return remote;
  }
}
